name: hello (develop)
on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  TEAM: dukerspace
  REPOSITORY: test
  TAG_NAME: main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        run: |
          docker build -t $TEAM/$REPOSITORY:$TAG_NAME .
          docker push $TEAM/$REPOSITORY:$TAG_NAME
          docker image rm $TEAM/$REPOSITORY:$TAG_NAME

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 120s
          script: |
            cd /var/www
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ env.TEAM }}/${{ env.REPOSITORY}}:${{ env.TAG_NAME }}
            docker-compose up -d --build
            docker image prune -f
            docker logout

      - name: Clean docker images in Runner
        run: |
          docker rmi $(docker images -q) -f
